#ifndef ENUM_H
#define ENUM_H

struct XY {
  double x;
  double y;
  XY() : x(0), y(0) {}
  XY(double x,double y) : x(x), y(y) {}
};

struct Rect {
  XY tl,
     tr,
     bl,
     br;
  Rect(XY tl, XY tr, XY bl, XY br) : tl(tl), tr(tr), bl(bl), br(br) { }
};
enum {
  DIRECTION_NORTH=0,
  DIRECTION_EAST=1,
  DIRECTION_SOUTH=2,
  DIRECTION_WEST=3
};
enum {
  MUSIC_INTRO=1000,
  MUSIC_TOWN,
  MUSIC_WANDERING,
  MUSIC_DESERT,
  MUSIC_FOREST,
  MUSIC_COMBAT1,
  MUSIC_COMBAT2,
  MUSIC_COMBAT3,
  MUSIC_FINALBATTLE,
  MUSIC_CREDITS
};
#define SOUND_UI_CLICK "./sounds/click.wav"
#define SOUND_UI_SELECT "./sounds/select.wav"

enum {
  EVENT_GAME_STARTED=11000,
  EVENT_GAME_ENDED,
  EVENT_BUTTON_CLICKED,
  EVENT_RENDER_FRAME,
  EVENT_KEYPRESS_DOWN,
  EVENT_KEYPRESS_UP,
  EVENT_SWITCH_STATES,
  EVENT_PLAY_MUSIC,
  EVENT_PLAY_SOUND,
  EVENT_CAMERA_TARGET,
  EVENT_CAMERA_MOVE_START,
  EVENT_CAMERA_MOVE_END,
  EVENT_COMMAND_USE_START,
  EVENT_COMMAND_USE_END,
  EVENT_SET_SPEED,
  EVENT_WINDOW_BUTTON_CLICKED,
  EVENT_BUTTON_PRESSED_DOWN,
  EVENT_BUTTON_PRESSED_RELEASE,
  EVENT_BUTTON_SELECTED,
  
  EVENT_COMBAT_STARTED,
  EVENT_COMBAT_ENDED,
  EVENT_UNIT_ATTACKS_DIRECTION,  //Unit Pointer, AttackNumber {1,2,3,4}, Direction
  EVENT_UNIT_USES_DIRECTION,     //Unit Pointer, Item Pointer, Direction
  EVENT_UNIT_USES_ON_SELF,       //Unit Pointer, Item Pointer
  EVENT_UNIT_CASTS_DIRECTION,    //Unit Pointer, Spell, Direction
  EVENT_UNIT_CASTS_ON_SELF,      //Unit Pointer, Spell
  EVENT_UNIT_HIT_UNIT_WITH,      //
  EVENT_PROJECTILE_HITS_UNIT,    //
  EVENT_UNIT_LEVELS_UP          //Skill UP
};


enum {
  STATE_INTRO,
  STATE_MENU,
  STATE_CHARACTER_SELECT,
  STATE_GAME
};
enum CLASSIFIER {
  SEA,
  GROUND,
  CLIFF 
};
enum {
//  TILE_GROUND_START=0,
  TILE_GRASS=0,
  TILE_WATER=8,
  TILE_SAND=1,
  TILE_DIRT=9,
  TILE_ROCKS,
  TILE_MUD,
  TILE_TALL_GRASS,
  TILE_PAVEMENT,
  TILE_COBBLESTONE,
//  TILE_GROUND_END,
//  TILE_SEA_START=8,
//  TILE_SEA_END,
//  TILE_CLIFF_START,
  TILE_MOUNTAIN,
  TILE_MOUNTAIN_PEAK,
  TILE_MOUNTAIN_LULL,
//  TILE_CLIFF_END
};

enum RESOURCE_TYPE {
  RESOURCE_SPRITESHEET,
  RESOURCE_MAPSHEET,
  RESOURCE_MUSIC,
  RESOURCE_SOUND
};
#endif