#ifndef ENUM_H
#define ENUM_H

struct XY {
  double x;
  double y;
  XY() : x(0), y(0) {}
  XY(double x,double y) : x(x), y(y) {}
};

struct Rect {
  XY tl,
     tr,
     bl,
     br;
  Rect(XY tl, XY tr, XY bl, XY br) : tl(tl), tr(tr), bl(bl), br(br) { }
};
enum {
  DIRECTION_NORTH=0,
  DIRECTION_EAST=1,
  DIRECTION_SOUTH=2,
  DIRECTION_WEST=3
};
enum {
  MUSIC_INTRO=1000,
  MUSIC_TOWN,
  MUSIC_WANDERING,
  MUSIC_DESERT,
  MUSIC_FOREST,
  MUSIC_COMBAT1,
  MUSIC_COMBAT2,
  MUSIC_COMBAT3,
  MUSIC_FINALBATTLE,
  MUSIC_CREDITS
};
enum {
  EVENT_GAME_STARTED=11000,
  EVENT_GAME_ENDED,
  EVENT_BUTTON_CLICKED,
  EVENT_RENDER_FRAME,
  EVENT_KEYPRESS_DOWN,
  EVENT_KEYPRESS_UP,
  EVENT_SWITCH_STATES,
  EVENT_PLAY_MUSIC,
  EVENT_CAMERA_TARGET,
  EVENT_CAMERA_MOVE_START,
  EVENT_CAMERA_MOVE_END,
  EVENT_SET_SPEED,
  EVENT_WINDOW_BUTTON_CLICKED
};
enum {
  STATE_INTRO,
  STATE_MENU,
  STATE_CHARACTER_SELECT,
  STATE_GAME
};
enum CLASSIFIER {
  SEA,
  GROUND,
  CLIFF 
};
enum {
//  TILE_GROUND_START=0,
  TILE_GRASS=0,
  TILE_WATER=8,
  TILE_SAND=1,
  TILE_DIRT=9,
  TILE_ROCKS,
  TILE_MUD,
  TILE_TALL_GRASS,
  TILE_PAVEMENT,
  TILE_COBBLESTONE,
//  TILE_GROUND_END,
//  TILE_SEA_START=8,
//  TILE_SEA_END,
//  TILE_CLIFF_START,
  TILE_MOUNTAIN,
  TILE_MOUNTAIN_PEAK,
  TILE_MOUNTAIN_LULL,
//  TILE_CLIFF_END
};
#endif